name: Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Alterado para JDK 17 (obrigatório para Gradle 9.x)
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      # Atualizado para v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Removido comando chmod, pois não existe gradlew
      # Executando diretamente o gradle global
      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload APK (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
